version:  '3.7'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure

  nginx:
    image: nginx:1.17.3-alpine
    restart: on-failure
    depends_on:
      - api
