version: '3.7'
services:
 api:
   volumes:
     - './apps/api/:/usr/src/app'

 nginx:
   volumes:
     - './apps/api/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
   ports:
     - '${NGINX_PORT}:80'